# Generated by Django 5.0.2 on 2024-03-05 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_app', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('experience', models.TextField()),
                ('about_coach', models.TextField()),
                ('area_of_interest', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
