# Generated by Django 5.0.2 on 2024-03-12 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_app', '0005_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
