# Generated by Django 5.0.2 on 2024-04-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_app', '0007_sports_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sports_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sports_type', models.CharField(max_length=20)),
                ('sports_minimum_duration', models.CharField(max_length=20)),
                ('Sports_charges', models.CharField(max_length=10)),
                ('sports_dress', models.FileField(upload_to='sa_app/sports_images')),
                ('sports_image', models.FileField(default='', upload_to='sa_app/sports_img')),
                ('sports_description', models.TextField(max_length=500)),
            ],
        ),
    ]
