# Generated by Django 5.0.2 on 2024-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_app', '0008_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('alternate_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('photo', models.FileField(default='', upload_to='sa_app/student_image')),
                ('sports_plan', models.CharField(max_length=10)),
                ('sports_name', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('fees', models.CharField(default='', max_length=10)),
                ('mode', models.CharField(default='', max_length=10)),
                ('transaction_no', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
